### ISSUE TITLE
vscode extension not working properly

### ISSUE THREAD

**Issue by nafis-ishrak** [deploifai/vscode-deploifai#12]
<img width="243" alt="image" src="https://github.com/deploifai/vscode-deploifai/assets/71823567/42d5f77b-d29d-4c72-a091-1cf9fba946f1">

**Comment by 98sean98** [comment]
I think there's something fundamentally wrong with the extension itself

**Comment by 98sean98** [comment]
The extension calls the `activate` function during initialization, and it seems like the `vscode.window.registerTreeDataProvider` function was not called [here](https://github.com/deploifai/vscode-deploifai/blob/022c1d2c694c49e9807f7562fc67505d9b57a36d/src/extension.ts#L68). I suspect some other errors were not handled properly, and so the `activate` function errored out.

Perhaps the auth state of the extension is not properly handled. It's very much possible that if the personal access token used to login to the extension in the first place was deleted from the user's developer settings in the main website, then the `init` function [here](https://github.com/deploifai/vscode-deploifai/blob/022c1d2c694c49e9807f7562fc67505d9b57a36d/src/extension.ts#L24) would throw an error due to the `getUserWorkspaces` function would throw an error because an invalid personal access token is provided to the api client.

I'm trying to handle these errors a bit better, and also checking if the stored credentials remain valid during `init` function call, by calling the `/auth/check/token` route in the backend server which validates if a given `username` and `token` pair remains valid. If the stored credentials are invalid, the `activate` function would remove the existing credentials, which effectively logs the user out. This should make the user login again.
